### PR TITLE
fix: linux game tracking and closed button

### LINKED ISSUE #1162: [BUG] playtime not tracked on linux
### Describe the bug

My playtime is not tracked when I play hydra games on Linux. When I play them on Windows, however, it does track it.

### Steps to Reproduce

1) install game on linux computer
2) play game
3) playtime is not tracked

### Expected behavior

Tracked playtime

### Additional information and data

Screenshot from 2024-10-28 20-50-59
It might just be a problem with wine idk

### Operating System

Arch Linux

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

### PR DESCRIPTION
**Pull request by JackEnx**
fix tracking gaming .exe on linux

close #1162

### CODE REVIEW

File: src/main/services/process-watcher.ts [hunk 1]
```diff
@@ -25,21 +25,43 @@ export const watchProcesses = async () => {
...
+
+      if (gameProcess) {
+        if (gamesPlaytime.has(game.id)) {
+          onTickGame(game);
+        } else {
+          onOpenGame(game);
+        }
+      } else if (gamesPlaytime.has(game.id)) {
+        onCloseGame(game);
+      }
```
Comment (zamitto) [inline src/main/services/process-watcher.ts:46]: This code is duplicated on lines 56-63. Maybe write a function for it?

**Review by zamitto — APPROVED** [review]
